[package]
name = "sara"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3

[dependencies]
avian2d = "0.3.1"
bevy = { version = "0.16.1" , features = ["dynamic_linking"] }
serde = { version = "1.0.219" , features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
